[package]
name = "hou"
version = "0.1.0"
authors = ["Nathan Ringo <nathan@remexre.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.2"
anyhow = "1.0.25"
lazy_static = "1.4.0"
