language: minimal
os: linux
services:
- docker
cache:
  bundler: true
  directories:
    - $HOME/docker

before_install:
- if [[ -e $HOME/docker/stahlos-builder.tgz ]]; then zcat $HOME/docker/stahlos-builder.tgz | docker load; fi
- docker build -t remexre/stahlos-builder .travis

script: docker run -v "$PWD:/code" --rm remexre/stahlos-builder bash /code/.travis/ci.sh

before_cache:
- mkdir -p $HOME/docker
- docker save remexre/stahlos-builder $(docker history -q remexre/stahlos-builder | grep -v missing) | gzip > $HOME/docker/stahlos-builder.tgz

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: out/docs
  keep-history: false
  on:
    branch: master
- provider: releases
  api_key: $GITHUB_TOKEN
  file: out/stahlos.img
  on:
    tags: true
  skip_cleanup: true
