\ The parts of the standard library that are implemented in Forth themselves.

\ Define function definition.
CREATE ' ] PARSE-NAME FIND-HEADER EXIT [ DOES>ENTER
CREATE POSTPONE ] ' HEADER>CFA COMPILE, EXIT [ DOES>ENTER IMMEDIATE

CREATE : ] CREATE ] EXIT [ DOES>ENTER
CREATE ;
  ' [ HEADER>CFA COMPILE,
  ] (LITERAL) EXIT COMPILE, DOES>ENTER EXIT [ DOES>ENTER IMMEDIATE

\ CREATE ; COMPILE, ' ] POSTPONE [ DOES>ENTER EXIT [ DOES>ENTER IMMEDIATE

DEBUG

: foo DEBUG ;
foo

: GT1 123 ;
' GT1 EXECUTE

DEBUG

\ vim: set cc=80 ft=forth ss=2 sw=2 ts=2 et :
