#!/usr/bin/env expect

proc shutdown {quit_after} {
	send "\003"
	set timeout 3
	expect {
		eof {
			if $quit_after {
				exit 1
			}
		}
		timeout {
			puts "QEMU didn't quit in time!"
			exit 2
		}
	}
}

proc wait_for {waiting_for line} {
	expect {
		$line {}
		eof {
			puts "QEMU crashed!"
			exit 3
		}
		timeout {
			puts "Timed out while waiting for ${waiting_for}!"
			shutdown true
		}
	}
}

puts "Starting expect tests..."

spawn qemu-system-x86_64 -cpu max -drive format=raw,file=out/stahlos.img,if=ide,media=disk -m 64M -machine q35 -display none -serial stdio

set timeout 30
wait_for "serial driver" "serial port inited!"
set timeout 5

shutdown false
# wait_for shutdown eof

puts "Expect tests passed!"
