#!/usr/bin/env expect

proc wait_for {waiting_for line} {
	expect {
		$line {}
		timeout {
			puts "Timed out while waiting for ${waiting_for}!"
			send "\001x"
			set timeout 3
			expect {
				eof { exit 1 }
				timeout {
					puts "QEMU didn't quit in time either!"
					exit 2
				}
			}
		}
	}
}

log_user 0
spawn qemu-system-x86_64 -drive format=raw,file=out/stahlos.img,if=ide,media=disk -m 64M -nographic

wait_for GRUB "Booting `StahlOS'"
set timeout 10

# Real tests should go here once serial works...

wait_for shutdown eof

puts "Expect tests passed!"
